export const FETCH_ACCOUNT_OVERVIEW_END = "FETCH_ACCOUNT_OVERVIEW_END";
export const RETRIEVE_API_KEY_FROM_LOCAL_STORAGE = "RETRIEVE_API_KEY_FROM_LOCAL_STORAGE";
export const SET_AUTH_HEADER = "SET_AUTH_HEADER";
export const UPDATE_API_KEY = "UPDATE_API_KEY";
export const LOGOUT = "LOGOUT";