export const UPDATE_SEND_SMS = "UPDATE_SEND_SMS";
export const RESET_DEFAULT_NEW_SMS = "RESET_DEFAULT_NEW_SMS";
export const QUEUE_DELIVERY_RECEIPT_CHECK = "QUEUE_DELIVERY_RECEIPT_CHECK";
export const REMOVE_REQUEST_ID_FROM_QUEUE = "REMOVE_REQUEST_ID_FROM_QUEUE";
export const SET_TOASTER_MESSAGE = "SET_TOASTER_MESSAGE";
export const DISMISS_TOASTER_MESSAGE = "DISMISS_TOASTER_MESSAGE";